## Numpy Array Operations

In [78]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
print("arr = ", arr)
print("Basic Slicing -> arr[ start: end]: ", arr[2:7])
print("Slicing with step -> arr[start: end: stepcount]: ", arr[1:8:2])
print("Negative indexing -> arr[- (index from end)]: ", arr[-4])

#For 2-D arrays

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr_2d:\n ", arr_2d)

print("Specific element -> arr_2d[row , column]: ", arr_2d[1,2])
print("Entire row -> arr_2d[row]: ", arr_2d[1])
print("Entire column -> arr[:, column]: ", arr_2d[:, 2])

arr =  [1 2 3 4 5 6 7 8 9]
Basic Slicing -> arr[ start: end]:  [3 4 5 6 7]
Slicing with step -> arr[start: end: stepcount]:  [2 4 6 8]
Negative indexing -> arr[- (index from end)]:  6
arr_2d:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element -> arr_2d[row , column]:  6
Entire row -> arr_2d[row]:  [4 5 6]
Entire column -> arr[:, column]:  [3 6 9]


## Sorting

In [85]:
unsorted = np.array([3,1,4,1,5,9,2,6])
sorted = np.sort(unsorted)
print("Sorted array: ", sorted)

#For 2-D arrays

arr_2d = np.array([[5,9],[8,2],[3,12]])

col_sorted = np.sort(arr_2d, axis = 0) # axis = 0 for columns
row_sorted = np.sort(arr_2d, axis = 1) # axis = 1 for rows

print("\nColumn sorted array: \n", col_sorted)

print("\nRow sorted array: \n", row_sorted)



Sorted array:  [1 1 2 3 4 5 6 9]

Column sorted array: 
 [[ 3  2]
 [ 5  9]
 [ 8 12]]

Row sorted array: 
 [[ 5  9]
 [ 2  8]
 [ 3 12]]


## FIlter

In [25]:

numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print("even numbers: ", numbers[numbers % 2== 0])


even numbers:  [ 2  4  6  8 10]


## Filter with Mask

In [27]:
mask = numbers > 5
print ("numebers greater than 5: ", numbers[mask])

numebers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing v/s np.where()

In [39]:
indices = [0,3,5]
# numbers[1,3,4] will give IndexError
print (numbers[indices])

where_result = np.where(numbers < 5)
print(where_result) #this will give indices of the array satisfying the condition given, here it is (numebrs < 5 )
print(numbers[where_result])


[1 4 6]
(array([0, 1, 2, 3]),)
[1 2 3 4]


In [41]:
condition_array = np.where(numbers>5, numbers, 0)
# np.where(contion, if condition is true, if condition is false)

"""
it works like this
np.where (condition, x, y)

{if (condition):
   returns x
else:
   returns y}
     
"""
print(condition_array)

[ 0  0  0  0  0  6  7  8  9 10]


## Adding or removing data

In [76]:
arr1 = ([1,2,3])
arr2 = ([4,5,6])

## arr1 + arr2 will simply add elements and return [5,7,9], so to combine the arrays we do ->

combined = np.concatenate((arr1,arr2))
print(combined)

## TO ADD NEW COLUMN or ROW

original = np.array([[1,2],[3,4]])
new_row = ([[5,6]])

with_new_row = np.vstack((original, new_row)) ##both arrays should have same dimension
print("With new row: \n", with_new_row)

new_col = ([5],[6])
with_new_col = np.hstack((original, new_col))
print("With new col: \n", with_new_col)


## TO DELETE

arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)
print("After deletion: ", deleted)




[1 2 3 4 5 6]
With new row: 
 [[1 2]
 [3 4]
 [5 6]]
With new col: 
 [[1 2 5]
 [3 4 6]]
After deletion:  [1 2 4 5 6]


## Array Compatibility

In [61]:
a = np.array ([1,2,3])
b = np.array ([4,5,6,11])
c = np.array ([7,8,9])

#compability with shape
print (a.shape == b.shape)
print (a.shape == c.shape)

#compability with dimension
print(a.ndim == b.ndim)

#with data type
print(a.dtype == b.dtype)

False
True
True
True
