## Numpy array and basis
learn about numpy

In [1]:
import numpy as np 

## creating array from list

In [2]:
arr_1D = np.array([1,2,3,4,5])
print ("1D array: ", arr_1D)

arr_2D = np.array([[1,2,3], [4, 5, 6]])
print("2D array: ", arr_2D)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1,2,3]
print("python list: ", py_list*2)

np_array = np.array([1,2,3])
print("python array: ", np_array*2)


import time

start = time.time()
py_list = [i*2 for i in range(100000)]
print ("\n time for list: ", time.time()-start )

start = time.time()
np_array = np.arange(100000)*2
print ("\n time for array: ", time.time()-start )


python list:  [1, 2, 3, 1, 2, 3]
python array:  [2 4 6]

 time for list:  0.004648685455322266

 time for array:  0.0


### Creating arrays from scratch

In [4]:
zeros = np.zeros((2,3))
print("zeros array: \n" ,zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,3), 7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,11,2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7 7]
 [7 7 7]]
random array: 
 [[0.40192511 0.96171187 0.95632274]
 [0.24592641 0.36789252 0.9299343 ]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [9]:
vector = np.array([1,2,3])

matrix = np.array([[1,2,3],
                  [4,5,6]])

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Vector : \n", vector)
print("Matrix : \n", matrix)
print("Tensor : \n", tensor)


Vector : 
 [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [12]:
arr = np.array([[1,2,3],
               [4,5,6]])

print ("arr.shape = ", arr.shape, " <- shows the (rows, columns) ->")
print ("arr.ndim = ", arr.ndim, " <- shows the 'dimension' -> ")
print ("arr.size = ", arr.size, " <- shows the 'size' ->")
print ("arr.dtype = ", arr.dtype, " <- shows the 'data type' -> ")

arr.shape =  (2, 3)  <- shows the (rows, columns) ->
arr.ndim =  2  <- shows the 'dimension' -> 
arr.size =  6  <- shows the 'size' ->
arr.dtype =  int64  <- shows the 'data type' -> 


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("\nOriginal array: \n", arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("\nFlattened array: \n", flattened )

raveled = reshaped.ravel()
print("\nRaveled array: \n", raveled)

#Transpose
transposed = reshaped.T
print("\nTransposed array : \n", transposed)




Original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
