## Matrix Operations

In [140]:
import numpy as np 
import time

# MATRIX MULTIPLICATION

A = np.array([[1,2,3],
                    [2,3,4],
                    [3,4,5]])

B = np.array([[3,4,1],
                    [2,5,6],
                    [3,1,2]])

print (" == Matrix Multiplication == \n")

print ("A.dot(B): \n",  A.dot(B), "\n")

print("np.dot(A,B): \n", np.dot(A,B), "\n")

print ("A@B: \n", A@B, "\n")

print ("np.matmul(A,B): \n", np.matmul(A,B), "\n")

# INVERSE OF A MATRIX
print ( "\n== Inverse of a Matrix ==")
print("np.linalg.inv(A): \n", np.linalg.inv(B), "\n") #will raise an error if the matrix is singular


 == Matrix Multiplication == 

A.dot(B): 
 [[16 17 19]
 [24 27 28]
 [32 37 37]] 

np.dot(A,B): 
 [[16 17 19]
 [24 27 28]
 [32 37 37]] 

A@B: 
 [[16 17 19]
 [24 27 28]
 [32 37 37]] 

np.matmul(A,B): 
 [[16 17 19]
 [24 27 28]
 [32 37 37]] 


== Inverse of a Matrix ==
np.linalg.inv(A): 
 [[ 0.07272727 -0.12727273  0.34545455]
 [ 0.25454545  0.05454545 -0.29090909]
 [-0.23636364  0.16363636  0.12727273]] 



In [144]:
# Eigen values of a Matrix
print("== Eigen values of a Matrix ==\n")

print("np.linalg.eigvals(A): ", np.linalg.eigvals(A) )


#Matrix raised to the power n
print("\nnp.linalg.matrix_power(A,n): \n", np.linalg.matrix_power(A,2))



== Eigen values of a Matrix ==

np.linalg.eigvals(A):  [ 9.62347538e+00 -6.23475383e-01  5.02863969e-16]

np.linalg.matrix_power(A,n): 
 [[14 20 26]
 [20 29 38]
 [26 38 50]]


### Decomposition

In [164]:
A = np.array([[0, 7, 1, 5],
              [5, 9, 2, 1],
              [2, 4, 6, 5],
              [5, 2, 4, 3]])
print(A)

#QR Decomposition
QR = np.linalg.qr(A) # can get both as Q,R = np.linalg.qr(A)
print("\nnp.linalg.qr(A): \n", QR,"\n Q = \n", QR[0],"\n R = \n", QR[1])
# QR[0] for Q, QR[1] for R



[[0 7 1 5]
 [5 9 2 1]
 [2 4 6 5]
 [5 2 4 3]]

np.linalg.qr(A): 
 QRResult(Q=array([[ 0.        ,  0.80032673, -0.05528263,  0.59701001],
       [-0.68041382,  0.36205257,  0.45799187, -0.44294291],
       [-0.27216553,  0.19055398, -0.88092646, -0.33702178],
       [-0.68041382, -0.43827416, -0.10562128,  0.57775163]]), R=array([[-7.34846923, -8.5732141 , -5.71547607, -4.0824829 ],
       [ 0.        ,  8.74642784,  0.91465912,  4.00163365],
       [ 0.        ,  0.        , -4.84734278, -4.53991742],
       [ 0.        ,  0.        ,  0.        ,  2.59025312]])) 
 Q = 
 [[ 0.          0.80032673 -0.05528263  0.59701001]
 [-0.68041382  0.36205257  0.45799187 -0.44294291]
 [-0.27216553  0.19055398 -0.88092646 -0.33702178]
 [-0.68041382 -0.43827416 -0.10562128  0.57775163]] 
 R = 
 [[-7.34846923 -8.5732141  -5.71547607 -4.0824829 ]
 [ 0.          8.74642784  0.91465912  4.00163365]
 [ 0.          0.         -4.84734278 -4.53991742]
 [ 0.          0.          0.          2.59025312]]


In [171]:
# Singular Values of A
singular_values = np.linalg.svdvals(A)
print("Singular Values of A: ", singular_values)

# SVD
SVD = np.linalg.svd(A)
print("SVD Decomposition of A: \n", SVD)



Singular Values of A:  [15.93535166  6.1411657   5.17828606  1.59248382]
SVD Decomposition of A: 
 SVDResult(U=array([[-0.47555805,  0.3562869 , -0.67747255,  0.43351486],
       [-0.60368357,  0.52980757,  0.53584918, -0.2602609 ],
       [-0.50967006, -0.55619421, -0.30626037, -0.58059368],
       [-0.3868425 , -0.53198833,  0.40012646,  0.63815368]]), S=array([15.93535166,  6.1411657 ,  5.17828606,  1.59248382]), Vh=array([[-0.37476239, -0.72633626, -0.39461417, -0.41984336],
       [-0.18291189,  0.64703073, -0.65935634, -0.33636839],
       [ 0.78546404, -0.06651887,  0.03035164, -0.61457324],
       [ 0.45732116, -0.22217585, -0.63922426,  0.57696412]]))


## Eigen values and vectors

In [180]:
#Eigen values and vector for a square matrix
square_matrix = np.linalg.eig(A) #If the matrix is not a square matrix it will give error
print(square_matrix)


# Norm, Length
print(np.linalg.norm(A)) #for both matrix and vectors
print(np.linalg.matrix_norm(A)) #for matrix


EigResult(eigenvalues=array([15.55830526, -5.28281446,  1.60427015,  6.12023905]), eigenvectors=array([[-0.42951279, -0.80115562, -0.45305101, -0.08815015],
       [-0.56315165,  0.26996604,  0.2036716 , -0.50852509],
       [-0.55426146, -0.17700865,  0.66081023,  0.72285908],
       [-0.4372336 ,  0.50392058, -0.56266553,  0.45946331]]))
17.916472867168917
17.916472867168917


In [ ]:
#Determinent of array or matrix
np.linalg.det(A)

np.float64(-807.0000000000002)

In [183]:
#Rank of a matrix
np.linalg.matrix_rank(A)

np.int64(4)

In [188]:
#trace 
np.trace(A) #for arrays

np.linalg.trace(A) #for matrix

np.int64(18)


## Solving System of Linear Equations

In [206]:
A = np.array([[1,-1,2],
              [2,1,4],
              [4,-1,1]])
B = np.array([2,7,4])
x = np.linalg.solve(A,B,) #for solution
print("Solution for System of equation: ", x)

y = np.allclose(np.dot(A,x), B) #to check, return boolean
print("Is solution correct: ", y)

#solving least square solution
least_sq = np.linalg.lstsq(A,B)
print("Least square solution: ", least_sq)



Solution for System of equation:  [1. 1. 1.]
Is solution correct:  True
Least square solution:  (array([1., 1., 1.]), array([], dtype=float64), np.int32(3), array([5.92139653, 2.90659926, 1.22014092]))


## Other operations

In [212]:
#diagonal
diag = np.diagonal(A)
print("Diagonals :", diag)

print(np.linalg.diagonal(A))

#Transpose 
transpose1 = A.T
transpose2 = np.linalg.matrix_transpose(A)

print(transpose1, "\n\n", transpose2)

Diagonals : [1 1 1]
[1 1 1]
[[ 1  2  4]
 [-1  1 -1]
 [ 2  4  1]] 

 [[ 1  2  4]
 [-1  1 -1]
 [ 2  4  1]]


In [256]:
#covariance of a matrix
cov = np.cov(A)
print(cov)


[[2.33333333 2.16666667 2.16666667]
 [2.16666667 2.33333333 0.83333333]
 [2.16666667 0.83333333 6.33333333]]


## Statistics

In [ ]:
np.median(A) #can do along a axis too, np.median(A,0/1)
np.average(A)
np.mean(A)
#standard deviation
np.std(A)
#variance
np.var(A)

#while ignoring nan - values
np.nanmedian(A)
np.nanmean(A)
np.nanstd(A)
np.nanvar(A)


np.float64(1.0)